
export interface PDFRoadmapData {
  title: string;
  description: string;
  topics: Array<{
    id: string;
    title: string;
    description: string;
    difficulty: string;
    estimatedTime: string;
    resources: Array<{
      title: string;
      url: string;
      type: string;
    }>;
  }>;
}

export const generateRoadmapPDF = async (roadmapData: PDFRoadmapData): Promise<void> => {
  // Create HTML content for PDF
  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>${roadmapData.title} - Learning Roadmap</title>
      <style>
        body { font-family: Arial, sans-serif; margin: 40px; color: #333; }
        .header { text-align: center; margin-bottom: 40px; border-bottom: 2px solid #4F46E5; padding-bottom: 20px; }
        .title { font-size: 32px; font-weight: bold; color: #4F46E5; margin-bottom: 10px; }
        .description { font-size: 16px; color: #666; line-height: 1.6; }
        .topic { margin-bottom: 30px; page-break-inside: avoid; }
        .topic-title { font-size: 20px; font-weight: bold; color: #1F2937; margin-bottom: 8px; }
        .topic-meta { font-size: 14px; color: #6B7280; margin-bottom: 10px; }
        .topic-description { font-size: 14px; line-height: 1.5; margin-bottom: 15px; }
        .resources { margin-left: 20px; }
        .resource { margin-bottom: 8px; font-size: 13px; }
        .resource-type { background: #E5E7EB; padding: 2px 6px; border-radius: 4px; font-size: 11px; margin-right: 8px; }
        .difficulty { display: inline-block; padding: 4px 8px; border-radius: 12px; font-size: 12px; font-weight: bold; }
        .beginner { background: #D1FAE5; color: #065F46; }
        .intermediate { background: #FEF3C7; color: #92400E; }
        .advanced { background: #FEE2E2; color: #991B1B; }
        .footer { margin-top: 40px; text-align: center; font-size: 12px; color: #9CA3AF; border-top: 1px solid #E5E7EB; padding-top: 20px; }
      </style>
    </head>
    <body>
      <div class="header">
        <div class="title">${roadmapData.title}</div>
        <div class="description">${roadmapData.description}</div>
      </div>
      
      ${roadmapData.topics.map(topic => `
        <div class="topic">
          <div class="topic-title">${topic.title}</div>
          <div class="topic-meta">
            <span class="difficulty ${topic.difficulty.toLowerCase()}">${topic.difficulty}</span>
            • Estimated Time: ${topic.estimatedTime}
          </div>
          <div class="topic-description">${topic.description}</div>
          <div class="resources">
            <strong>Resources:</strong>
            ${topic.resources.map(resource => `
              <div class="resource">
                <span class="resource-type">${resource.type}</span>
                <a href="${resource.url}" target="_blank">${resource.title}</a>
              </div>
            `).join('')}
          </div>
        </div>
      `).join('')}
      
      <div class="footer">
        <p>Generated by DevPath - Your Learning Journey Companion</p>
        <p>Visit us at devpath.com for interactive learning experiences</p>
      </div>
    </body>
    </html>
  `;

  // Create and download PDF
  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(htmlContent);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
    }, 500);
  }
};
