// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://onedhgkuwvhywthqmgod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9uZWRoZ2t1d3ZoeXd0aHFtZ29kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NjU1MTMsImV4cCI6MjA3MjA0MTUxM30.zJ0rTmlyHfh8w0rW9CWQAaTTv8yP3nFRAGbB_RB6itQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});